alter table b_shelf add column http_link varchar(200);
INSERT INTO `b_shelf` (`id`, `country`, `language`, `dialect`, `b_code`, `title`, `description`, `translated_by`, `copyright`, `license`, `table_name`, `http_link`) VALUES (NULL, 'Italy', 'Italian', 'Italian', 'it-it_http', 'Italian Bible', 'Italian Bible of John Hurt', NULL, '<a href="http://johnhurt.com/johnhurt.com/italian/about.htm" target="_blank">John Hurt</a>', 'Public Domain', '', 'http://johnhurt.com/johnhurt.com/italian/index.htm');
INSERT INTO `b_shelf` (`id`, `country`, `language`, `dialect`, `b_code`, `title`, `description`, `translated_by`, `copyright`, `license`, `table_name`, `http_link`) VALUES (NULL, 'Romania', 'Romanian', 'Romanian', 'ro-ro_http', 'Rumanian Bible', 'Romanian Bible of John Hurt', '<a href="http://www.htmlbible.com/sacrednamebiblecom/rumanian/about.htm" target="_blank">John Hurt</a>', NULL, 'Public Domain', NULL, 'http://www.htmlbible.com/sacrednamebiblecom/rumanian/index.htm');
INSERT INTO `b_shelf` (`id`, `country`, `language`, `dialect`, `b_code`, `title`, `description`, `translated_by`, `copyright`, `license`, `table_name`, `http_link`) VALUES (NULL, 'Ukraine', 'Ukrainian', 'Ukrainian', 'ua-ua_http', 'Ukrainian Bible', 'Ukrainian Bible of John Hurt', NULL, '<a href="http://www.htmlbible.com/sacrednamebiblecom/ukrainian/about.htm" target="_blank">John Hurt</a>', 'Public Domain', NULL, 'http://www.htmlbible.com/sacrednamebiblecom/ukrainian/index.htm');
INSERT INTO `b_shelf` (`id`, `country`, `language`, `dialect`, `b_code`, `title`, `description`, `translated_by`, `copyright`, `license`, `table_name`, `http_link`) VALUES (NULL, 'South Korea', 'Korean', 'Korean', 'ko-kr_http', 'Korean Bible', 'Korean Bible', NULL, '<a href="http://www.christianisrael.com/korean/about.htm" target="_blank">Christian Israel</a>', 'Public Domain', NULL, 'http://www.christianisrael.com/korean/index.htm');
INSERT INTO `b_shelf` (`id`, `country`, `language`, `dialect`, `b_code`, `title`, `description`, `translated_by`, `copyright`, `license`, `table_name`, `http_link`) VALUES (NULL, 'Vietnam', 'Vietnamese', 'Vietnamese', 'vi-vn_http', 'Vietnamese Bible', 'Vietnamese Bible of John Hurt', NULL, '<a href="http://www.htmlbible.com/sacrednamebiblecom/vietnamese/about.htm" target="_blank">John Hurt</a>', 'Public Domain', NULL, 'http://www.htmlbible.com/sacrednamebiblecom/vietnamese/index.htm');
INSERT INTO `b_shelf` (`id`, `country`, `language`, `dialect`, `b_code`, `title`, `description`, `translated_by`, `copyright`, `license`, `table_name`, `http_link`) VALUES (NULL, 'Netherlands', 'Dutch', 'Dutch', 'nl-nl_http', 'Nederlands Staten Vertalings 1715 Bijbel', 'Dutch Bible of John Hurt', NULL, '<a href="http://johnhurt.com/johnhurt.com/dutch/about.htm" target="_blank">John Hurt</a>', 'Public Domain', NULL, 'http://johnhurt.com/johnhurt.com/dutch/index.htm');
INSERT INTO `b_shelf` (`id`, `country`, `language`, `dialect`, `b_code`, `title`, `description`, `translated_by`, `copyright`, `license`, `table_name`, `http_link`) VALUES (NULL, 'Bulgaria', 'Bulgarian', 'Bulgarian', 'bg-bg_http', 'Bulgarian Bible', 'Bulgarian Bible of John Hurt', NULL, 'Christian Israel', 'Public Domain', NULL, 'http://www.christianisrael.com/bulgarian/index.htm');
INSERT INTO `b_shelf` (`id`, `country`, `language`, `dialect`, `b_code`, `title`, `description`, `translated_by`, `copyright`, `license`, `table_name`, `http_link`) VALUES (NULL, 'Sweden', 'Swedish', 'Swedish', 'sv-se_http', 'BIBEL Neller DEN HELIGA SKRIFT
KONUNGEN ÅR 1917', 'Swedish Bible of John Hurt', NULL, '<a href="http://www.htmlbible.com/sacrednamebiblecom/swedish/about.htm" target="_blank">John Hurt</a>', 'Public Domain', NULL, 'http://www.htmlbible.com/sacrednamebiblecom/swedish/index.htm');
INSERT INTO `b_shelf` (`id`, `country`, `language`, `dialect`, `b_code`, `title`, `description`, `translated_by`, `copyright`, `license`, `table_name`, `http_link`) VALUES (NULL, 'Hungaria', 'Hungarian', 'Hungarian', 'hu-hu_http', 'Hungarian Bible', 'Hungarian Bible of John Hurt', NULL, '<a href="http://www.htmlbible.com/sacrednamebiblecom/hungarian/about.htm" target="_blank">John Hurt</a>', 'Public Domain', NULL, 'http://www.htmlbible.com/sacrednamebiblecom/hungarian/index.htm');
INSERT INTO `b_shelf` (`id`, `country`, `language`, `dialect`, `b_code`, `title`, `description`, `translated_by`, `copyright`, `license`, `table_name`, `http_link`) VALUES (NULL, 'Denmark', 'Danish', 'Danish', 'da-dk_http', 'Danske Bibelen', 'Danish Bible of John Hurt', NULL, NULL, 'Public Domain', NULL, 'http://johnhurt.com/johnhurt.com/danish/index.htm');
INSERT INTO `b_shelf` (`id`, `country`, `language`, `dialect`, `b_code`, `title`, `description`, `translated_by`, `copyright`, `license`, `table_name`, `http_link`) VALUES (NULL, 'Finland', 'Finnish', 'Finnish', 'fi-fi_http', 'Finnish Bible', 'Finnish Bible of John Hurt', NULL, NULL, 'Public Domain', NULL, 'http://johnhurt.com/johnhurt.com/finnish/index.htm');
INSERT INTO `b_shelf` (`id`, `country`, `language`, `dialect`, `b_code`, `title`, `description`, `translated_by`, `copyright`, `license`, `table_name`, `http_link`) VALUES (NULL, 'Haiti', 'Haitian Creole', NULL, 'ht-ht_http', 'Haitian Creole Bible', 'Haitian Creole Bible of John Hurt', NULL, '<a href="http://johnhurt.com/johnhurt.com/haitian_creole/about.htm" target="_blank">John Hurt</a>', 'Public Domain', NULL, 'http://johnhurt.com/johnhurt.com/haitian_creole/index.htm');
INSERT INTO `b_shelf` (`id`, `country`, `language`, `dialect`, `b_code`, `title`, `description`, `translated_by`, `copyright`, `license`, `table_name`, `http_link`) VALUES (NULL, 'Croatia', 'Croatian Bible', NULL, 'hr-hr_http', 'Croatian Bible', 'Croatian Bible of John Hurt', NULL, NULL, 'Public Domain', NULL, 'http://www.christianisrael.com/croatian/index.htm');
INSERT INTO `b_shelf` (`id`, `country`, `language`, `dialect`, `b_code`, `title`, `description`, `translated_by`, `copyright`, `license`, `table_name`, `http_link`) VALUES (NULL, 'Norway', 'Norwegian', NULL, 'no-no_http', 'Norwegian Bible', 'Norwegian Bible of Christian Israel', NULL, NULL, 'Public Domain', NULL, 'http://www.christianisrael.com/norwegian/index.htm');
-- Latvian
-- Albanian
-- Swahili